<h2 id="get-characters">Notification token</h2>
<p>
    Use this <strong>(https://YOUR-SITE.COM/mobile_api/save_pnotif_token)</strong> API to access the Notification Token Management Endpoint
</p>
<br>
<h4 class="table-title">Post parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>token</td>
            <td>Push notification token</td>
            <td>
                E.g. c625cc16eb0096...
            </td>
        </tr>
        <tr>
            <td>type</td>
            <td>Client device type</td>
            <td>
                ios/android (Default is android)
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "err_code": "0",
    "code": 200,
    "message": "Notification token saved",
    "data": []
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data":[],
    "message": "Unauthorized Access"
}

{
    "err_code": "invalid_token",
    "code": 400,
    "message": "Incorrect token value",
    "data": []
}
</code></pre>
    </div>
</div>