<h2 id="get-bookmarks">Get bookmarks</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/get_bookmarks)</strong> API for accessing get user bookmarks endpoint
</p>
<br>
<h4 class="table-title">Get parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>page_size</td>
            <td>​Total post limit for each request</td>
            <td>
                Recommended: 20
            </td>
        </tr>
        <tr>
            <td>offset</td>
            <td>Last post offset ID</td>
            <td>
                This is only needed when loading posts of the pagination system.
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "err_code": 0,
    "valid": true,
    "code": 200,
    "message": "Bookmarks fetched successfully",
    "data":[
        {"id": 36, "user_id": 7, "text": "retw", "type": "text", "replys_count": "1",…},
        {"id": 38, "user_id": 7, "text": "ert", "type": "text",…},
        {"id": 39, "user_id": 7, "text": "ert", "type": "text",…},
        {"id": 40, "user_id": 7, "text": "erter", "type": "text",…}
    ]
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}

{
    "err_code": 0,
    "code": 204,
    "message": "No data found",
    "data": []
}
</code></pre>
    </div>
</div>