<h2 id="get-settings">Get Privacy settings</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/get_priv_settings) API for accessing the endpoint of user privacy settings</strong> 
</p>
<br>
<h4 class="table-title">Get parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 200,
    "valid": true,
    "message": "",
    "data":{
        "profile_visibility": "everyone",
        "contact_privacy": "everyone",
        "search_visibility": true
    }
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}
</code></pre>
    </div>
</div>