<h2 id="get-settings">Change Privacy settingss</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/set_priv_settings) API for accessing the endpoint of changing user privacy settings</strong> 
</p>
<br>
<h4 class="table-title">Post parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>profile_visibility</td>
            <td>​Profile access privacy</td>
            <td>
                E.g. One of these options (followers/nobody/everyone)
            </td>
        </tr>
        <tr>
            <td>contact_privacy</td>
            <td>Direct message privacy</td>
            <td>
                E.g. One of these options (followed/everyone)
            </td>
        </tr>
        <tr>
            <td>search_visibility</td>
            <td>​Profile search indexing privacy</td>
            <td>
                E.g. One of these options (Y/N)
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 200,
    "valid": true,
    "message": "User privacy settings updated",
    "data": []
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}

{
    "err_code": "invalid_[ Invalid field name ]",
    "code": 400,
    "data": [],
    "message": "Invalid request data"
}
</code></pre>
    </div>
</div>