<h2 id="get-characters">Follow & Unfollow user</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/follow) API for access (follow/unfollow) user endpoint</strong> 
</p>
<br>
<h4 class="table-title">Post parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>user_id</td>
            <td>​Followed/Un​followed user int ID</td>
            <td>
                E.g. 4567
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 200,
    "valid": true,
    "message": "",
    "data": {
        "follow": true
    }
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}

{
    "code": 400,
    "err_code": "invalid_request_data",
    "message": "User ID is missing or invalid",
    "data": []
}
</code></pre>
    </div>
</div>