<h2 id="get-characters">Repost Post</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/publication_repost) API for access publication repost endpoint</strong> 
</p>
<br>
<h4 class="table-title">Post parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>post_id</td>
            <td>​Liked/Unliked post int ID</td>
            <td>
                E.g. 4567
            </td>
        </tr>
        <tr>
            <td>message</td>
            <td>​Additional Message when reposting</td>
            <td>
                Ignored for now, as the script kernel does not support it
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "post_reposts": 1,
    "valid": true,
    "message": "",
    "code": 200,
    "data":{
        "repost": true
    }
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}


{
    "code": 400,
    "err_code": "invalid_request_data",
    "message": "Post id is missing or invalid",
    "data": []
}
</code></pre>
    </div>
</div>