<h2 id="get-characters">Verify user account</h2>
<p>
    Please use this <strong>(https://YOUR-SITE.COM/mobile_api/verify_user)</strong> API for accessing a user account verification endpoint
</p>
<br>
<h4 class="table-title">Post parameters</h4>
<table>
    <thead>
    <tr>
        <th width="15%">Field</th>
        <th width="25%">Value</th>
        <th width="45%">Remarks</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>session_id</td>
            <td>​Access token ID</td>
            <td>
                E.g. de25cc16eb00960f076...
            </td>
        </tr>
        <tr>
            <td>text_message</td>
            <td>​Text message to the reviewer</td>
            <td>
                E.g. "Please verify my account"
            </td>
        </tr>
        <tr>
            <td>video_message</td>
            <td>Video message to the reviewer</td>
            <td>
                E.g. "video appeal.mp4"
            </td>
        </tr>
        <tr>
            <td>full_name</td>
            <td>​User full name</td>
            <td>
                E.g. John Smith
            </td>
        </tr>
    </tbody>
</table>
<h4 class="table-title">Success response</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
	"status": 400,
	"err_code": 0,
	"code": 200,
	"valid": true,
	"message": "Verification request sent successfully"
}
</code></pre>
    </div>
</div>
<h4 class="table-title">Error responses</h4>
<div class="code-holder">
    <div class="code-holder-inner">
<pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}

{
	"code": 400,
	"data": [],
	"message": "Your account has already been verified"
}

{
	"err_code": "duplicate_request_error",
	"code": 400,
	"message": "Error Duplicate request. Please wait until the end of the review of the previous request",
	"data": []
}

{
	"err_code": "invalid_full_name",
	"code": 400,
	"message": "Invalid user full name. Please check your details",
	"data": []
}

{
	"err_code": "invalid_text_message",
	"code": 400,
	"message": "Text message to the reviewer is incorrect or missing",
	"data": []
}

{
	"err_code": "invalid_video_message",
	"code": 400,
	"message": "Video message to the reviewer is incorrect or missing",
	"data": []
}

{
	"err_code": "unknown_server_error",
	"code": 500,
	"message": "An error occurred while processing your request. Please try again later.",
	"data": []
}
</code></pre>
    </div>
</div>